### ISSUE TITLE
Only one encoder in trainer.py

### ISSUE THREAD

**Issue by petruskkke** [Wenchao-Du/LIR-for-Unsupervised-IR#1]
Hi. The paper says there are two encoders (generators) for the clean image and noisy image splitly. However, I can only find one generator 'gen_a' in 'train.py'. I think that it is the generator for noisy image. Where is the defination of the other generator (for clean image)? Thansk in advance.

**Comment by Wenchao-Du** [comment]
> Hi. The paper says there are two encoders (generators) for the clean image and noisy image splitly. However, I can only find one generator 'gen_a' in 'train.py'. I think that it is the generator for noisy image. Where is the defination of the other generator (for clean image)? Thansk in advance.

Yes, the code has been updated for training. Original code has removed the clean encoder branch for testing, you can update the code for customer training.
