### ISSUE TITLE
Noise types?

### ISSUE THREAD

**Issue by QLaHPD** [Wenchao-Du/LIR-for-Unsupervised-IR#9]
It is expected that other types of noise are possible to be learned by the network, for example, JPEG artifacts?

**Comment by Wenchao-Du** [comment]
of course, you could prepare your own data for training, e.g., jpeg artifacts images, but some hyper-parameters may be changed.

**Comment by QLaHPD** [comment]
Just to be sure, does the code expect only noise images inside the root folder?
What are subdivisions A and B (I noticed celeba_A/B subfolders in utils.py)?

**Comment by Wenchao-Du** [comment]
> Just to be sure, does the code expect only noise images inside the root folder?
> What are subdivisions A and B (I noticed celeba_A/B subfolders in utils.py)?
we need the unpaired training data, i.e., noisy data and clean data. As shown in codes, one is the clean data root, and another is noisy data root.

**Comment by QLaHPD** [comment]
Okay, thank you.

**Comment by haolin512900** [comment]
> > 可以肯定的是，代码是否只需要根文件夹内的噪声图像？
> > 什么是细分 A 和 B（我注意到 utils.py 中的 celeba_A/B 子文件夹）？
> > 我们需要未配对的训练数据，即噪声数据和干净数据。如代码所示，一个是干净数据根，另一个是噪声数据根。

Does the clean data set come from the VOC data set? So do you need to search for noise data by yourself? Where is the noise data set used by the author? Is the clean data set put into Celeba_A, and then the noise data set into Celeba_B?
